### ISSUE TITLE
Bloodmoom PfP Patch is deprecated.

### ISSUE THREAD

**Issue by zertyuiop** [Necrolesian/morrowind-mod-list#2]
Bloodmoom PfP Patch is deprecated.

_Originally posted by @zertyuiop in https://github.com/Necrolesian/morrowind-mod-list/issues/1#issuecomment-1166500686_

**Comment by Necrolesian** [comment]
if you examine the plugins in tes3view you'll see that bloodmoon rebalance 1.2 still misses a few pfp fixes, and a patch is needed for those

but the old patch is no longer available on alvazir's nexus page, so i uploaded a minimal one with just the fixes needed and updated the list with the new link, plus an explanation for why the patch is still needed
