### ISSUE TITLE
Vivec and Velothi Arkitektora Atlas Bug

### ISSUE THREAD

**Issue by zertyuiop** [Necrolesian/morrowind-mod-list#3]
There are a few issues with this mod, in particular when using the UHQ option, the temple in Balmora is completely black. Also in the comments to the mod, there are problems with the HQ version, it is suggested to use the MQ version, with which, as mentioned, there are no problems. I only had a problem with the Balmora temple, changing UHQ to HQ solves it, but there may be problems with it.

**Comment by Necrolesian** [comment]
i modified the instructions to make clear some users might need to use the MQ file. it depends on the graphics card, the HQ file is too big for some (like UHQ is too big for mine, but HQ works fine).
