### ISSUE TITLE
HD Clutter and Atlas Texture Collection

### ISSUE THREAD

**Issue by zertyuiop** [Necrolesian/morrowind-mod-list#5]
The instructions for the Atlas Texture Collection have a list of textures that must be installed if the list is followed. However, it further states to install textures for urns that are in the texture list, but without specifying the desired option, it is assumed that the Dunmeri Urns option is needed, and redware that is not in the texture list, it is assumed that the HD Clutter option should be used, but if selected, it will completely replace the Atlas textures from HD Clutter installed in the previous step.

**Comment by Necrolesian** [comment]
fixed, thank you! i specified which urns texture to install. the redware texture is covered by HD Clutter, i had just forgotten to remove that reference to it before
