### ISSUE TITLE
Morowind Anti-Cheese Tweaked loaded after BTBGI means no Daedric Towershield

### ISSUE THREAD

**Issue by dev-chenxing** [Necrolesian/morrowind-mod-list#6]
Both Morowind Anti-Cheese Tweaked and BTBGI edit golden saint_staada. BTBGI gives Staada the only Daedric Towershield in the game and Morowind Anti-Cheese Tweaked's Staada edit overrides it. **I think** we should either delete the Staada edit in Morowind Anti-Cheese Tweaked or load it before BTBGI. 

In a post in #morrowind-sharp, Sigourn stated: 

> This ESP loads after BTBGI instead of before it (in order to override the value of Scrap Metal). The guide's load order has been adjusted. 

So doing the latter means the value of Scrap Metal goes from 200g to 30g, which I don't really care about. 

Here's the items on Staada if we load BTBGI after Morrwoind Anti-Cheese Tweaked. 
![Staada](https://user-images.githubusercontent.com/109032964/187871583-cfe038b1-5be7-4162-ac40-1ec43d07cb4a.png)

**Comment by dev-chenxing** [comment]
Also, I write a few mlox rules for this modlist, could you please take a look and confirm they are in the correct order? Or did I miss some rules that also need to be added? Thank you so much. 
```
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; @Patch for Purists

[Order]
Patch for Purists - Book Typos.esp
Patch for Purists - Semi-Purist Fixes.esp

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; @Hospitality_Papers_Expanded

[Order]
Patch for Purists - Book Typos.esp
Hospitality_Papers_Expanded*.esp

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; @Divayth Fyr Puzzle Fixed Ownership Overhaul Patch

[Order]
Divayth Fyr Puzzle Fixed.ESP
Divayth Fyr Puzzle Fixed Ownership Overhaul Patch.ESP

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; @Glass Domes of Vivec_atmospheric arena Ownership Overhaul Patch

[Order]
Glass Domes of Vivec_atmospheric arena.esp
Glass Domes of Vivec_atmospheric arena Ownership Overhaul Patch.ESP

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; @Expansion Integrated MDMD Patch

[Order]
MDMD - More Deadly Morrowind Denizens.ESP
MDMD - Creatures Add-On.ESP
Expansions Integrated MDMD Patch.ESP

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; @There Can Be Only One Expansions Integrated Patch

[Order]
Expansions Integrated.esp
There Can Be Only One Expansions Integrated Patch.ESP

[Order]
There Can Be Only One.ESP
There Can Be Only One Expansions Integrated Patch.ESP

[Order]
There Can Be Only One (Alt Fyr).ESP
There Can Be Only One Expansions Integrated Patch.ESP

[Order]
There Can Be Only One (Alt Fyr 2).ESP
There Can Be Only One Expansions Integrated Patch.ESP

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; @There Can Be Only One MDMD Patch

[Order]
MDMD - More Deadly Morrowind Denizens.esp
There Can Be Only One MDMD Patch.ESP

[Order]
MDMD - More Deadly Morrowind Denizens.esp
There Can Be Only One (Alt Fyr) MDMD Patch.ESP

[Order]
MDMD - More Deadly Morrowind Denizens.esp
There Can Be Only One (Alt Fyr 2) MDMD Patch.ESP

[Order]
There Can Be Only One.ESP
There Can Be Only One MDMD Patch.ESP

[Order]
There Can Be Only One (Alt Fyr).ESP
There Can Be Only One (Alt Fyr) MDMD Patch.ESP

[Order]
There Can Be Only One (Alt Fyr 2).ESP
There Can Be Only One (Alt Fyr 2) MDMD Patch.ESP

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; @BTB's Game Improvements (Necro Edit)

[Order]
Patch for Purists - Semi-Purist Fixes.ESP
BTB's Game Improvements (Necro Edit).esp

[Order]
Patch for Purists - Merged Fixes.esp.ESP
BTB's Game Improvements (Necro Edit).esp

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; @BTBGI MDMD - Creatures Patch

[Order]
MDMD - Creatures Add-On.esp
BTBGI MDMD - Creatures Patch.esp

[Order]
BTB's Game Improvements (Necro Edit).esp
BTBGI MDMD - Creatures Patch.esp

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; @Rebalance Series BTBGI Patch

[Order]
tribunal rebalance.ESP
Rebalance Series BTBGI Patch.ESP

[Order]
Bloodmoon Rebalance.esp
Rebalance Series BTBGI Patch.ESP

[Order]
Beware the Sixth House.esp
Rebalance Series BTBGI Patch.ESP
```

**Comment by Necrolesian** [comment]
Thank you for the report! :)

Does tes3merge not fix the issue with Staada for you? There's actually an updated version of tes3merge by rfuzzo that I haven't had a chance to try out yet. IIUC it has an "inclusive merge" option that changes how inventory changes are merged. But I think the older tes3merge handled Staada correctly?

If tes3merge doesn't fix it, then for right now I'm okay with just deleting the Staada reference from MAC. Eventually I plan on just adding the MAC edits I think make a lot of sense to BTBGI, and getting rid of the rest, but that'll probably be a while.

And those mlox rules look correct as far as order is concerned, but I think the filename is MDMD Expansions Integrated Patch.ESP

**Comment by Necrolesian** [comment]
Okay I tested with the old tes3merge (which the list still links to for now) and it does not fix Staada's inventory. I didn't test it with TCBOO and other mods also enabled, which also touch Staada, but it's probably the same.

So for right now I just say to delete the Staada reference from the plugin.

This list is in sore need of a major update, but, you know, time lol.

**Comment by dev-chenxing** [comment]
> but I think the filename is MDMD Expansions Integrated Patch.ESP

Thank you for the reply. My Expansions Integrated MDMD Patch comes from [MDMD - More Deadly Morrowind Denizens Patches-49232-1-1-1647014361.7z](https://www.nexusmods.com/morrowind/mods/49232?tab=files&file_id=1000029669). But I also notice there is an MDMD Expansions Integrated Patch 1.2.1 in the Archived files section so I'm gonna send both rules to the mlox-rules people.
