### ISSUE TITLE
Bookart Replacer PFP Fixes link missing

### ISSUE THREAD

**Issue by Lavamob64** [Necrolesian/morrowind-mod-list#7]
The link to the replacement plugin for the Bookart Replacer mod leads to a 404 page on GitHub. https://github.com/Sigourn/morrowindsharp/raw/master/mods/Comrade%20Raven's%20Book%20Arts%20(PfP%20Edit).7z

**Comment by dev-chenxing** [comment]
This is the correct link. 
https://github.com/Sigourn/morrowindsharp/raw/main/mods/Comrade%20Raven's%20Book%20Arts%20(PfP%20Edit).7z

**Comment by Lavamob64** [comment]
Thank you!

**Comment by Necrolesian** [comment]
Link updated, thank you!
